baseURL = "https://huuphat.github.io/"
languageCode = "vi-VN"
title = "Há»¯u PhÃ¡t Blog"
theme = "hugo-profile"

# ======================
# MENU (THANH ÄIá»€U HÆ¯á»šNG)
# ======================
[menu]
  [[menu.main]]
    name = "Vá» TÃ´i"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Chá»©ng chá»‰"
    url = "/certificates"
    weight = 2

  [[menu.main]]
    name = "Äá»“ Ã¡n"
    url = "/projects"
    weight = 3
    
  [[menu.main]]
    name = "BÃ i Viáº¿t"
    url = "/posts"
    weight = 4

# ======================
# Cáº¤U HÃŒNH CHUNG (PARAMS)
# ======================
[params]
  title = "Há»¯u PhÃ¡t"
  description = "Sinh viÃªn CÃ´ng nghá»‡ ThÃ´ng tin - HUTECH"
  avatar = "avatar.jpg"
  
  # Link file CSS tÃ¹y chá»‰nh
  customCSS = ["css/custom.css"] 

# ======================
# PHáº¦N HERO (TRANG CHá»¦)
# ======================
[params.hero]
  enable = true
  intro = "Xin chÃ o, tÃ´i lÃ "
  title = "Há»¯u PhÃ¡t"
  
 # === ÄÃƒ Sá»¬A Láº I ===
  # Theme khÃ´ng nháº­n HTML, nÃªn mÃ¬nh viáº¿t tÃ¡ch dÃ²ng báº±ng phÃ­m Enter bÃ¬nh thÆ°á»ng
  # DÃ¹ng 3 dáº¥u nhÃ¡y Ä‘Æ¡n (''') Ä‘á»ƒ xuá»‘ng dÃ²ng Ä‘Æ°á»£c
  subtitle = '''
  LÃ m tá»‡ viá»‡c nÃ o Ä‘Ã³ lÃ  bÆ°á»›c Ä‘áº§u tiÃªn Ä‘á»ƒ giá»i Ä‘Æ°á»£c viá»‡c Ä‘Ã³ ğŸš€
  '''
  
  # === ÄÃƒ Sá»¬A: THÃŠM áº¢NH BÃŠN PHáº¢I ===
  # Nhá»› lÃ m BÆ°á»›c 1: Äá»•i tÃªn áº£nh thÃ nh hero.jpg vÃ  bá» vÃ o static/images/
  image = "/hero.jpg"


# ======================
# Máº NG XÃƒ Há»˜I
# ======================
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/phatphat292"

[[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/huuu.phatt.868718"

[[params.socialIcons]]
  name = "email"
  url = "mailto:phatpham581@gmail.com"


# ======================
# PHáº¦N LIÃŠN Há»†
# ======================
[params.contact]
  enable = true
  title = "LiÃªn Há»‡"
  
  content = '''
  Náº¿u báº¡n quan tÃ¢m Ä‘áº¿n profile cá»§a tÃ´i hoáº·c muá»‘n há»£p tÃ¡c, Ä‘á»«ng ngáº§n ngáº¡i káº¿t ná»‘i nhÃ©!
  
  ğŸ“§ [Email: phatpham581@gmail.com](mailto:phatpham581@gmail.com)
  
  ğŸ“˜ [Facebook CÃ¡ NhÃ¢n](https://www.facebook.com/huuu.phatt.868718)
  
  ğŸ™ [Github Profile](https://github.com/phatphat292)
  '''
  
  email = "phatpham581@gmail.com"
  btnName = "Gá»­i Email Ngay"


# ======================
# Cáº¤U HÃŒNH KHÃC
# ======================
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# ======================
# Cáº¤U HÃŒNH DANH SÃCH BÃ€I VIáº¾T (RECENT POSTS)
# ======================
[params.posts]
  enable = true
  title = "CÃ¡c bÃ i Blog gáº§n Ä‘Ã¢y"      
  subtitle = "Chia sáº» kiáº¿n thá»©c vá» Máº¡ng mÃ¡y tÃ­nh, DevOps vÃ  Láº­p trÃ¬nh"
  recentPostsCount = 3                
  showDate = true                     
  showDescription = true              
  viewAllPost = true                  
  viewAllPostText = "Xem táº¥t cáº£ â†’"