baseURL = "https://huuphat.github.io/"
languageCode = "vi-VN"
title = "Há»¯u PhÃ¡t Blog"
theme = "hugo-profile"

# ======================
# MENU (THANH ÄIá»€U HÆ¯á»šNG)
# ======================
[menu]
  [[menu.main]]
    name = "Vá» TÃ´i"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Chá»©ng chá»‰"
    url = "/certificates"
    weight = 2

  [[menu.main]]
    name = "Äá»“ Ã¡n"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "BÃ i Viáº¿t"
    url = "/posts" # Hoáº·c "#posts" náº¿u muá»‘n trÆ°á»£t trÃªn trang chá»§
    weight = 4

# ======================
# Cáº¤U HÃŒNH CHUNG (PARAMS)
# ======================
[params]
  title = "Há»¯u PhÃ¡t"
  description = "Sinh viÃªn CÃ´ng nghá»‡ ThÃ´ng tin - HUTECH"
  avatar = "avatar.jpg"
  
  # Link file CSS tÃ¹y chá»‰nh (Äá»ƒ áº©n ngÃ y thÃ¡ng nhÆ° Ä‘Ã£ lÃ m)
  customCSS = ["css/custom.css"] 

# ======================
# PHáº¦N HERO (TRANG CHá»¦)
# ======================
[params.hero]
  enable = true
  intro = "Xin chÃ o, tÃ´i lÃ "
  title = "Há»¯u PhÃ¡t"
  subtitle = "ChÃ o má»«ng Ä‘áº¿n vá»›i blog cÃ¡ nhÃ¢n cá»§a tÃ´i "


# ======================
# Máº NG XÃƒ Há»˜I
# ======================
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/phatphat292"

[[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/huuu.phatt.868718"

[[params.socialIcons]]
  name = "email"
  url = "mailto:phatpham581@gmail.com"


# ======================
# PHáº¦N LIÃŠN Há»† (Sá»¬ Dá»¤NG MARKDOWN)
# ======================
[params.contact]
  enable = true
  title = "LiÃªn Há»‡"
  
  # DÃ¹ng 3 dáº¥u nhÃ¡y Ä‘Æ¡n (''')
  # Sá»­ dá»¥ng cÃº phÃ¡p Markdown: [TÃªn hiá»ƒn thá»‹](ÄÆ°á»ng dáº«n)
  content = '''
  Náº¿u báº¡n quan tÃ¢m Ä‘áº¿n profile cá»§a tÃ´i hoáº·c muá»‘n há»£p tÃ¡c, Ä‘á»«ng ngáº§n ngáº¡i káº¿t ná»‘i nhÃ©!
  
  ğŸ“§ [Email: phatpham581@gmail.com](mailto:phatpham581@gmail.com)
  
  ğŸ“˜ [Facebook CÃ¡ NhÃ¢n](https://www.facebook.com/huuu.phatt.868718)
  
  ğŸ™ [Github Profile](https://github.com/phatphat292)
  '''
  
  email = "phatpham581@gmail.com"
  btnName = "Gá»­i Email Ngay"


# ======================
# Cáº¤U HÃŒNH KHÃC
# ======================
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# ======================
# Cáº¤U HÃŒNH DANH SÃCH BÃ€I VIáº¾T (RECENT POSTS)
# ======================
[params.posts]
  enable = true
  title = "CÃ¡c bÃ i Blog gáº§n Ä‘Ã¢y"      # TiÃªu Ä‘á» to
  subtitle = "Chia sáº» kiáº¿n thá»©c vá» Máº¡ng mÃ¡y tÃ­nh, DevOps vÃ  Láº­p trÃ¬nh" # DÃ²ng chá»¯ nhá» bÃªn dÆ°á»›i
  recentPostsCount = 3                # Sá»‘ lÆ°á»£ng bÃ i muá»‘n hiá»‡n (nÃªn Ä‘á»ƒ 3 hoáº·c 6 cho Ä‘áº¹p Ä‘á»™i hÃ¬nh)
  showDate = true                     # Hiá»‡n ngÃ y Ä‘Äƒng
  showDescription = true              # Hiá»‡n mÃ´ táº£ ngáº¯n
  viewAllPost = true                  # Hiá»‡n nÃºt "Xem táº¥t cáº£"
  viewAllPostText = "Xem táº¥t cáº£ â†’"    # Chá»¯ trÃªn nÃºt